CXX = g++

all: delayedremovetag.cpp noop.cpp number.cpp removetag.cpp removetag0.cpp 
	$(CXX) delayedremovetag.cpp -o delayedremovetag 
	$(CXX) noop.cpp -o noop 
	$(CXX) number.cpp -o number 
	$(CXX) removetag.cpp -o removetag 
	$(CXX) removetag0.cpp -o removetag0 